### ISSUE TITLE
Prerelease tags handling too strict for Rust versions

### ISSUE THREAD

**Issue by SimonSapin** [dtolnay/semver#105]
I am trying to update https://github.com/Kimundi/rustc-version-rs from semver 0.1 to 0.2 (in order to reduce the number of crates with more than one versions in Servo’s dependency graph).

One of its tests is that the current Rust version matches `>= 1.0.0`. On beta or nightly, with a version like `Version { major: 1, minor: 17, patch: 0, pre: [AlphaNumeric("nightly")], build: [] }`, this test fails. This seems to be because of the `pre_tag_is_compatible` method which has a comment with the URL https://docs.npmjs.com/misc/semver#prerelease-tags

There we can read:

> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.

[...]

> The purpose for this behavior is twofold. First, prerelease versions frequently are updated very quickly, and contain many breaking changes that are (by the author's design) not yet fit for public consumption. Therefore, by default, they are excluded from range matching semantics.

But this description does not apply to Rust at all. Rust Nightly is not expected to contain breaking changes from 1.0.0. Bugs happen of course, but they’re the exception rather than the rule.

Is it possible to opt into a different behavior such that `rustc_version::version_matches(">= 1.0.0")` is true on Nightly?

**Comment by steveklabnik** [comment]
> Is it possible to opt into a different behavior such that rustc_version::version_matches(">= 1.0.0") is true on Nightly?

This is a good question, and I don't know the answer.

I mean, the short answer is "no", but I'm not sure how to do this for `rustc` without breaking everything else.

**Comment by dtolnay** [comment]
https://github.com/dtolnay/semver/issues/172 has some discussion of this issue. (This one was filed first, but that one has the discussion. :shrug:) I'll close this one to keep it in one place.
