### ISSUE TITLE
Implement serde Serialize/Deserialize for VersionReq

### ISSUE THREAD

**Issue by brson** [dtolnay/semver#119]
Only when the "serde" feature is enabled. It's implemented for `Version` but not `VersionReq`. I imagine this wants a custom serializer, not a derived one. Maybe @steveklabnik you can say more about how this should be implemented and tag it help wanted.

**Comment by steveklabnik** [comment]
I'm not sure what the use-case is, so I'm not sure why it'd want to be custom.

**Comment by brson** [comment]
Sounds like it can just be auto-derived then.

**Comment by brson** [comment]
Oh, actually, my use case was to deserialize version requirements from the crates.io API into a VersionReq. I presume that would require a custom serializer / deserializer, but don't know for sure. In the crates.io API they are just strings that are shaped like version requirements.

**Comment by steveklabnik** [comment]
Yeah I mean, one problem with `VersionReq` generally is that there's no "normal form" for them; that is, you could construct two different `VersionReq`s with different constraints that result in the same set of versions, so they wouldn't be equal to each other anymore... I'm wondering if that's an issue with serialization.

Maybe trying out the default one and seeing if it works for crates.io is the right call.

**Comment by KodrAus** [comment]
Is this all sorted now?

**Comment by opilar** [comment]
Seems it's already in release 0.8.0. Should be ok.

**Comment by valarauca** [comment]
As of `0.9.0` this does not appear to work.

**Comment by dtolnay** [comment]
This was implemented in #122.
