### ISSUE TITLE
VersionReq incorrectly matches on prerelease versions

### ISSUE THREAD

**Issue by steveklabnik** [dtolnay/semver#124]
This should fail, but passes: https://play.rust-lang.org/?gist=fb9ab8b08c460ff4b0bb514f560cb079&version=stable

Originally found in https://github.com/rust-lang/cargo/issues/4479

**Comment by dtolnay** [comment]
I believe the current implementation is consistent with the behavior described for caret comparators in https://github.com/semver/semver/blob/efcff2c838c9945f79bfd21c1df0073271bcc29c/ranges.md (modulo the typo in https://github.com/semver/semver/pull/584#discussion_r634040432). `^0.11.0-rc.2` is equivalent to `>=0.11.0-rc.2, <0.12.0-0`, and nothing there suggests to me that it shouldn't match `0.11.0`.
