### ISSUE TITLE
Make error types non-exhaustive

### ISSUE THREAD

**Issue by KodrAus** [dtolnay/semver#135]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-struct-private)

Using `enum`s for capturing possible error cases is convenient, but it can be tricky for future-proofing because adding new variants is a breaking change because users can exhaustively match them.

We should think about how we can make the error types more resilient to future changes by either:

- Adding a non exhaustive variant (until we've got a stable `#[non_exhaustive]` attribute this could be a hidden variant with an ugly name, like `#[doc_hidden] __NonExhaustive`)
- Refactoring the errors into structures with private fields

The first option is a good step, but we would need to be careful about adding new variants that change the conditions under which other variants are returned. This would be a semantic breaking change. The second option is less ergonomic for downstream users, but provides the best future-proofing.

I think this will need some more discussion to come up with a design we're all happy with going forward to `1.0`.

# Mentoring instructions

Leave a comment here on the thread and we'll work out how to get started.

**Comment by EverlastingBugstopper** [comment]
`#[non_exhaustive]` is now stable :) would be a breaking change to introduce this but might be worth revisiting

**Comment by dtolnay** [comment]
The error type in 1.0.0 no longer publicly exposes variants.
