### ISSUE TITLE
Make fields on `Version` private

### ISSUE THREAD

**Issue by KodrAus** [dtolnay/semver#136]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-struct-private)

The `Version` type currently uses public fields, which is convenient for construction and destructuring, but not ideal for future-proofing. It means new fields can't be added to `Version` without a breaking change, and the types of those fields are fixed (the `pre: Vec<Identifier>` field couldn't be changed into `pre: [Identifier; 4]` for example).

We should come up with a design for `Version` that offers the future-proofing guarantees we want without sacrificing more ergonomics than necessary.

**Comment by KodrAus** [comment]
I posted this on the `internals` thread, but this is what I came up with when I tried to hide all the fields on `Version`:

```rust
pub struct Version {
    major: u64,
    minor: u64,
    patch: u64,
    pre: Pre,
    build: Build,
}

pub struct Pre(Vec<Identifier>);
pub struct Build(Vec<Identifier>);

pub struct Iter<'a>(std::slice::Iter<'a, Identifier>);
pub struct IntoIter(std::vec::IntoIter<Identifier>);

impl Version {
    pub fn major(&self) -> u64;
    pub fn minor(&self) -> u64;
    pub fn patch(&self) -> u64;
    pub fn pre(&self) -> &Pre;
    pub fn build(&self) -> &Build;

    pub fn as_parts(&self) -> (u64, u64, u64, &Pre, &Build);
    pub fn into_parts(self) -> (u64, u64, u64, Pre, Build);
}

impl Pre {
    pub fn iter(&self) -> Iter;
}

impl FromIterator<Identifier> for Pre {
    ...
}

impl IntoIterator for Pre {
    type Item = Identifier;
    type IntoIter = IntoIter;

    ...
}

impl<'a> IntoIterator for &'a Pre {
    type Item = &'a Identifier;
    type IntoIter = Iter<'a>;

    ...
}

impl Extend<Identifier> for Pre {
    ...
}

impl Build {
    pub fn iter(&self) -> Iter;
}

impl FromIterator<Identifier> for Build {
    ...
}

impl IntoIterator for Build {
    type Item = Identifier;
    type IntoIter = IntoIter;

    ...
}

impl<'a> IntoIterator for &'a Build {
    type Item = &'a Identifier;
    type IntoIter = Iter<'a>;

    ...
}

impl Extend<Identifier> for Build {
    ...
}
```

We could simplify it a bit by making `Pre` and `Build` use the same types.

**Comment by bobbo** [comment]
I'm hacking on this one

**Comment by bobbo** [comment]
@KodrAus, I've taken a quick stab at this, would be good to get some high level feedback before I (hopefully) tidy it up & submit as MR: https://github.com/steveklabnik/semver/compare/master...bobbo:issue-136?expand=1

I don't like `MultiPartIdentifier` being quite as verbose as it is, so any suggestions on that welcome.

**Comment by KodrAus** [comment]
@bobbo Yeh that's pretty much what I was thinking. One thing I would change though is instead of:

```diff
- type Iter<'a> = ::std::slice::Iter<'a, Identifier>;
- type IntoIter = ::std::vec::IntoIter<Identifier>;
+ pub struct Iter<'a>(::std::slice::Iter<'a, Identifier>);
+ pub IntoIter(::std::vec::IntoIter<Identifier>);
```

That's more a personal opinion though, since the type aliases you introduced aren't publicly exported they're kind of like using `impl Trait`, but I do like being able to see all publicly visible items in the crate docs.

The `MultiPartIdentifier` name seems fine to me. People won't be directly using it much, right?

**Comment by KodrAus** [comment]
How's it going @bobbo? Are you still looking into this one and is there anything I can do to help out?

**Comment by bobbo** [comment]
Hey @KodrAus, still looking at this, just struggling to find time to polish the branch up to PR-readiness. Should have more time in the week coming.

**Comment by dtolnay** [comment]
The representation of `Prerelease` and `BuildMetadata` has been made private in 1.0.0. The representation of `Version` is fine to leave public outside of those two things, as they were the main future compatibility concerns.

https://docs.rs/semver/1.0.0-rc.1/semver/struct.Version.html
