### ISSUE TITLE
Support range sets

### ISSUE THREAD

**Issue by KodrAus** [dtolnay/semver#137]
This would depend on https://github.com/steveklabnik/semver-parser/issues/22

The npm `semver` package [supports parsing sets of versions](https://docs.npmjs.com/misc/semver#ranges) separated by some operator. It would be great if they were also supported here in `semver`, but would need to be implemented in `semver_parser` first.

Once `semver_parser` has a type for representing ranges, we could make `VersionReq` use that type internally, where ranges with a single comparator are equivalent to its behaviour today.

Let's discuss this over in https://github.com/steveklabnik/semver-parser/issues/22 first, and then come back here when it's possible to implement in `semver`.

# Mentoring instructions

See https://github.com/steveklabnik/semver-parser/issues/22 first.

**Comment by dtolnay** [comment]
This is out of scope for this crate, since we're deliberately matching Cargo's interpretation of SemVer and not any other implementation's, like npm. Adding range set support to Cargo would need to go through a Cargo RFC.
