### ISSUE TITLE
Deprecate WildcardVersion::Major?

### ISSUE THREAD

**Issue by udoprog** [dtolnay/semver#150]
Hey,

I'm currently trying to do a comparison for when a `VersionReq` is a full wildcard: `*`.

For all intents and purposes, the following states of `VersionReq` appears to be equivalent:
 * `predicates` is empty, causing the `all` check to return `true`.
 * there is one predicate, whose `op` is `Op::Wildcard(WildcardVersion::Major)`.

Both of these cases appears to match _any_ version. Both of them are `fmt::Display`:ed in a way so that they show `*`.

I would like to discuss if we could either have `VersionReq::any()` return the same as when `*` is parsed (single `WildcardVersion::Major` predicate) to make comparisons viable. Or to completely deprecate the use of `WilcardVersion::Major` since its functionality is equivalent to an empty set of predicates.

**Comment by steveklabnik** [comment]
This is a good question! I'm not sure.

**Comment by udoprog** [comment]
For my specific problem, introducing a function like `is_wildcard` would also work:
https://github.com/udoprog/semver/commit/c27a8c9ebf1b3393f500cab05a5d5bd9c36b437b

**Comment by steveklabnik** [comment]
I've accepted the underlying PR in semver-parser, so we can do this here too.

**Comment by udoprog** [comment]
I've rebased #151. When version 0.8.0 of semver-parser is available it is good to go.
I've also closed #159 since you'll be taking this approach.

Thanks!

**Comment by dtolnay** [comment]
This is fixed in 1.0.0. The `*` requirement is now uniformly represented with an empty comparator set, and there is no WildcardVersion::Major.
