### ISSUE TITLE
Add an "is subset of" check for VersionReq

### ISSUE THREAD

**Issue by est31** [dtolnay/semver#156]
VersionReq is essentially a set of versions that it matches on. It would be cool if you could compare to VersionReq instances a and b and check whether one a is a subset of b, aka if a is fulfilled, then b is too.

This relation is a partial order (the subset relation is always a partial order on any set of sets), but no total order, as some elements are not comparable to each other. I however don't suggest changing the derived PartialOrd/Ord implementations, as then you wouldn't have Ord around (or you'd have the Ord implementation be inconsistent with the PartialOrd implementation -- that would be something that the two traits forbid). Whether the current derived, and thus lexicographic, Ord implementation makes any sense or not is a different question and best left to a different issue, it definitely doesn't have any semantic meaning.

**Comment by dtolnay** [comment]
Closing as per https://github.com/dtolnay/semver/pull/224#pullrequestreview-668100702. I would prefer if this were implemented downstream for now. If it turns up in lots of projects, we can re-evaluate.

**Comment by est31** [comment]
@dtolnay as you've closed this issue out of concerns about the popularity of this feature, [if you sort by number of :+1: votes](https://github.com/dtolnay/semver/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc), the four upvotes make this the most upvoted issue in the semver tracker, sharing the first spot with #184 .

**Comment by dtolnay** [comment]
I understand. Previously this was not possible to implement downstream, and now it is, so the number of old votes is not compelling.

**Comment by cecton** [comment]
hmmm... :thinking: I can imagine someone will make a crate expressly for that XD It's not super trivial to implement
