### ISSUE TITLE
Failed parse of compound version req

### ISSUE THREAD

**Issue by dherman** [dtolnay/semver#183]
Parsing of the compound version req `">=0.10.0 <0.12"` fails, but I think it’s a valid semver specifier?

[repro](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=03412db067e5594066b865d54f42be8a)

**Comment by passcod** [comment]
The underlying parser crate works fine, as a datapoint: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=da6d5d804797f45adae04406a05ece7b

**Comment by dtolnay** [comment]
Cargo doesn't accept this style, and so I'll consider it out of scope for this crate. Once there is a Cargo RFC to accept this and Cargo is on board, we can update the implementation here.
