### ISSUE TITLE
Default implementation

### ISSUE THREAD

**Issue by skyne98** [dtolnay/semver#184]
Hey there, I think it would be beneficial to add a "Default" trait implementation for "Version" and maybe "VersionReq" structs.

Should there be any complications in the process?

Thanks!

**Comment by zzeroo** [comment]
This could be easy made I think. But whats the benefit of such?

**Comment by skyne98** [comment]
Oh, that was a pretty long time ago. I think it is related to `Version` being serializable, which, as far as I remember, requires the data type to have an implementation of default. Moreover, I think it's beneficial to have `Default` implemented for any kind of data type to allow users to just use `Default::default()` on initializing complex data structures!

**Comment by skyne98** [comment]
I think it might be a good idea to fall back to something like "0.0.0" as the default for `Version` and "no requirements" for the `VersionReq` if the last is possible.

**Comment by SimonWoodburyForget** [comment]
There are multiple benefits, for example when initializing the `Version` struct with existing version numbers:

```rust
let major = 1;
let minor = 120;
let version = Version {
    major,
    minor,
    ..Default::default()
};
```

Another issue is if you have a type which requires a default implementation in order to be statically safe, then you can't use `Version` inside of it without using `Option`:

```rust
#[derive(Default)]
struct App {
    version: Version,
}
```

**Comment by dtolnay** [comment]
Would someone be able to point out some concrete real-world code in which this Default impl would be beneficial, and how that code is currently working around it?

**Comment by dtolnay** [comment]
I've closed the issue because my impression is this isn't needed, but anyone should feel free to follow up if they can provide a compelling use case in real-world code (with a link to real code).
