### ISSUE TITLE
Add a method to check if all Predicates in some VersionReq contains some Op

### ISSUE THREAD

**Issue by hbina** [dtolnay/semver#191]
Hello,

I am trying to resolve this issue here : https://github.com/rust-lang/cargo/issues/5340
But to do that --- without resorting to copying the behavior of `VersionReq` --- I would need an API that can easily let me check if all of my `Predicate`s in some `VersionReq` matches some `Op`.

I would like something like this to be possible,

`(semver::VersionReq).contains_op(semver::Op)`.

I believe this will require couple of changes:

1. Op is now a public enum
2. Add a new method `contains_op` that takes an `Op` and returns a `bool` as described above.

Thank you!

**Comment by dtolnay** [comment]
As of 1.0.0, this logic is now possible to implement downstream, and doesn't need to be built into this crate.

```rust
use semver::{Op, VersionReq};

fn contains_op(req: &VersionReq, op: Op) -> bool {
    req.comparators.iter().all(|cmp| cmp.op == op)
}
```
