### ISSUE TITLE
[feature request] public way to declare a VersionReq without a parse()

### ISSUE THREAD

**Issue by kentfredric** [dtolnay/semver#202]
I find myself currently in a situation where I'd like to, in code, declare a large volume of `VersionReq` entries statically.

And while the simplicity of the `parse("string here")` syntax is nice, having to wrap it in a runtime error handling chain is not ideal.

Perhaps even a `macro!`  could suffice here, but the overwhelming goal is to provide a way to have statically defined `VersionReq`'s, and if there are any errors in their definition, it should be a *compile time* failure, not a runtime failure which must be handled.

**Comment by dtolnay** [comment]
Fixed in 1.0.0: https://docs.rs/semver/1.0.0-rc.1/semver/struct.VersionReq.html
