### ISSUE TITLE
Version ordering up to a certain level?

### ISSUE THREAD

**Issue by tarquin-the-brave** [dtolnay/semver#208]
Hi,

I recently found myself in the need of assessing whether two versions were within the same minor release.  I put together this little hack of a function, that wasn't perfect (didn't deal with pre V1 semver versions properly), but did the immediate job OK for my use case:

```rust
fn minor_or_major_bump(old: &semver::Version, new: &semver::Version) -> bool {
    let new = semver::Version {
        major: new.major,
        minor: new.minor,
        patch: 0,
        pre: vec![],
        build: vec![],
    };

    let old = semver::Version {
        major: old.major,
        minor: old.minor,
        patch: 0,
        pre: vec![],
        build: vec![],
    };

    new > old
}
```

Essentially I zero'd out the version components below the level I cared about (minor), then leveraged current ordering.

I then though WIBNI `semver::Version` could "just do this".

I haven't got particularly far in thinking what this would actually look like, but keen to start or join a discussion.  Maybe something like methods to establish order and equality at each level? (`eq_major`, `gt_minor`, etc)

Interested to know what people think

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate. If you have evidence of the same logic appearing in lots of different projects, I can reevaluate.
