### ISSUE TITLE
Documentation Needs Fixing or Clarification

### ISSUE THREAD

**Issue by abellgithub** [dtolnay/semver#214]
The following statement from the doc is confusing.

> Caret requirements allow SemVer compatible updates to a specified version, `0.x` and `0.x+1` are not considered compatible, but `1.x` and `1.x+1` are.

Is there something special about version 0? Does this JUST apply to 0.1 and 0.2? What about 0.0.1 and 0.0.2? Rather than an example, stating the actual rule might be helpful.

**Comment by dtolnay** [comment]
I've updated the documentation to state this more precisely. https://docs.rs/semver/1.0.0-rc.1/semver/enum.Op.html#opcaretcompatible-updates

<br>

![Screenshot from 2021-05-25 11-05-29](https://user-images.githubusercontent.com/1940490/119546760-2111a980-bd49-11eb-9646-178d63e1b5fe.png)
