### ISSUE TITLE
semver v0.11 regression parsing openssl-src VersionReqs

### ISSUE THREAD

**Issue by tarcieri** [dtolnay/semver#217]
See this RustSec PR and the versioning scheme used by the `openssl-src` crate:

- https://github.com/RustSec/advisory-db/pull/450
- https://crates.io/crates/openssl-src/versions

`semver` versions v0.10 and earlier were able to parse these requirements:

- `>= 111.9.0+1.1.1g`
- `< 111.6.0+1.1.1d`

With v0.11 I get the following error:

> the given version requirement is invalid

Per the PR I'm trying to work around the issue by using a wildcard.

**Comment by steveklabnik** [comment]
Interesting, these should be valid versions. Thanks / sorry.

**Comment by Turbo87** [comment]
we've noticed similar issues when we tried to upgrade `semver` in the crates.io codebase. specifically version requirements like https://github.com/dhylands/serial-monitor/blob/71e52ac9b66fd999681e5fbbb8ac415a36e69bd2/Cargo.toml#L26 are failing to parse, even though they can be parsed as a regular `Version`.

I've created https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6726d4731dd480fb26a48b2ed29ec491 to reproduce the problem.

**Comment by pione30** [comment]
I've also noticed that some pre-release fields like `alpha.1a` cannot be parsed as `VersionReq` on `semver` v0.11, while they are correctly parsed as `Version`:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6d7008e0bea904e17957909182e4bb1e

**Comment by dtolnay** [comment]
Relevant issue in the `semver-parser` crate, which is where the `semver` crate delegates to for the parsing logic: https://github.com/steveklabnik/semver-parser/issues/55.

**Comment by dtolnay** [comment]
This is fixed in 1.0.0.
