### ISSUE TITLE
Add a way to get the minimum VersionReq that matches a version

### ISSUE THREAD

**Issue by sunshowers** [dtolnay/semver#226]
It would be cool to have a way to convert a version to a minimum VersionReq that matches, for example:

1.2.0 --> ^1
0.4.5 --> ^0.4
0.0.7 --> =0.0.7
anything with a prerelease should be treated exactly
not sure about build metadata

This isn't a very rigorous definition yet, but curious to hear ideas.

**Comment by dtolnay** [comment]
I think I would prefer not to expose this directly in this crate, but as of 1.0.0 it's now possible to implement such a thing downstream. If the same logic turns up in lots of projects, we can reevaluate.

**Comment by mirao** [comment]
Related stuff:
The npm's [semver](https://www.npmjs.com/package/semver) allows getting of min/max boundary for a given version:
```ts
import { toComparators } from "semver"
console.log(toComparators("~1.2.0"));
```
This is output:
`[ [ '>=1.2.0', '<1.3.0-0' ] ]`

It's useful for testing: https://nodesource.com/blog/semver-tilde-and-caret/
Is it possible to get it with Rust's `semver`?

**Comment by sunshowers** [comment]
For the problem I described in the OP, here's what I wrote as the solution: https://github.com/guppy-rs/guppy/blob/448d830de4867c32eaa57911a392e47c81d1a0e0/tools/hakari/src/helpers.rs#L7-L96

**Comment by mirao** [comment]
@sunshowers Thank you, I will look at it.
Just found a handy cargo tool that does the same as npm's `semver`: https://crates.io/crates/semver-explain
E.g. for the version `1.2.0` you get `>=1.2.0, <2.0.0` ([the same result as with caret](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements): `^1.2.0`) whereas npm's module prints `[ [ '1.2.0' ] ]` which is expected difference from Cargo.
