### ISSUE TITLE
VersionReq may panic .Found by afl.rs

### ISSUE THREAD

**Issue by StevenJiang1110** [dtolnay/semver#227]
I've using [afl.rs](https://github.com/rust-fuzz/afl.rs) to fuzz this crate. And I found a panic issue in VersionReq. The code to replay the issue is
```rust
let _ = semver::VersionReq::parse("80000000000000000000");
```
And from the panic reportn, it seems that this panic is caused by use unwrap on a Result which may return err.
<img width="1375" alt="截屏2021-01-09 下午9 56 44" src="https://user-images.githubusercontent.com/27764680/104093457-9bbfb800-52c5-11eb-9c60-c87fe97cc07f.png">
I hope you can check if this is a bug need to be fixed. Thanks a lot.

**Comment by dtolnay** [comment]
Thanks &mdash; this is fixed in 1.0.0 and I've put fuzz target for parsing into the repo.
