### ISSUE TITLE
Removed Version Mutability?

### ISSUE THREAD

**Issue by DeveloperC286** [dtolnay/semver#243]
Hi,

First of all thank you for all the work you have done in creating this crate. 

I am using Semver Version `0.11.0` and making use of functions that mutate the Version e.g. `version.increment_patch();` etc. When attempting to upgrade to the latest SemVer Version `1.0.1` it seems this functionality has been removed? I am aware this is a major version bump so there is the possibility of breaking changes. It appears this crate has underwent a complete rewrite, will this functionality be reimplemented or is it no longer behaviour the crate will support?

Regards,
DeveloperC

**Comment by dtolnay** [comment]
That's right, this is no longer exposed. If you need to reproduce the previous behavior it can be written as:

```rust
use semver::{BuildMetadata, Prerelease, Version};

fn increment_patch(v: &mut Version) {
    v.patch += 1;
    v.pre = Prerelease::EMPTY;
    v.build = BuildMetadata::EMPTY;
}

fn increment_minor(v: &mut Version) {
    v.minor += 1;
    v.patch = 0;
    v.pre = Prerelease::EMPTY;
    v.build = BuildMetadata::EMPTY;
}

fn increment_major(v: &mut Version) {
    v.major += 1;
    v.minor = 0;
    v.patch = 0;
    v.pre = Prerelease::EMPTY;
    v.build = BuildMetadata::EMPTY;
}
```

**Comment by BrettMayson** [comment]
Is the reason for this change documented anywhere?
