### ISSUE TITLE
About "invalid leading zero in pre-release identifier"

### ISSUE THREAD

**Issue by dalance** [dtolnay/semver#246]
https://github.com/dtolnay/semver/issues/230 changed the behavior of `Version::parse`.
I agree "0.3.0-alpha.01" is invalid, but crates.io/Cargo allows the invalid version now.
So this changing causes the [all index of crates.io](https://github.com/rust-lang/crates.io-index) can't be handled by semver crate.

I think the invalid version should be handled because semver crate says "Cargo's interpretation of Semantic Versioning".
For example, `Version::parse` allows the invalid version, and `Version::parse_strict` disallows.

What do you think?

**Comment by dtolnay** [comment]
Cargo's interpretation changed as of https://github.com/rust-lang/cargo/pull/9508 (including a number of other incompatibilities between old Cargo and the spec) and it no longer considers that to be a valid version.

```toml
[package]
name = "testing"
version = "0.3.0-alpha.01"
```

```console
$ cargo check
error: failed to parse manifest at `/repro/Cargo.toml`

Caused by:
  invalid leading zero in pre-release identifier for key `package.version`
```

**Comment by dalance** [comment]
Thank you for your quick reply.
I'll ignore the invalid version crates as the same as cargo.

**Comment by dtolnay** [comment]
Sounds good. If invalid crates in the crates.io index or crates.io database is sufficiently troublesome for many people, the correct place to follow up would be with crates.io, since that is really their problem. I imagine they may consider deleting such crates from the index and database, or tweaking the versions.

**Comment by dalance** [comment]
Yes. I think this is not troublesome because almost people see the index through cargo.
I realized this issue because I see the index directly through [cargo-trend](https://github.com/dalance/cargo-trend).
The fix of cargo-tally https://github.com/dtolnay/cargo-tally/commit/ed92dcdd6977e50c7c7d7b2c6982c01871dd3255 looks good too.
