### ISSUE TITLE
How to sort a list by the latest version

### ISSUE THREAD

**Issue by navarroaxel** [dtolnay/semver#248]
Hi,

I'm parsing Yum repositories and I need to find the `latest` version for a package.

How can I implement this kind of sort?

```rust
repository
  .packages
  .iter()
  .sorted_by(|a, b| ...)
  .unique_by(|pkg| &pkg.name)
  .map(|pkg| YumUpdate {
    name: pkg.name.clone(),
    version: pkg.versions.first().unwrap().version.clone(),
  })
```

I tried `Version::parse` but I can't find a comparator to find the greatest/latest semver version. Thanks!

Full code here: https://github.com/navarroaxel/archlinux-checkupdates-external/blob/main/crates/yum/src/fetch.rs#L29

**Comment by ehuss** [comment]
`Version` implements `PartialOrd` and `Ord`, so you can just compare them using normal comparison methods.  There is a detailed description of ordering [in the docs](https://docs.rs/semver/1.0.3/semver/struct.Version.html#total-ordering).
