### ISSUE TITLE
nonzero_leading_trailing_zeros requires rustc 1.53.0

### ISSUE THREAD

**Issue by xd009642** [dtolnay/semver#249]
`NonZeroUsize::leading_zeros` was made stable/const in 1.53.0 https://doc.rust-lang.org/std/num/struct.NonZeroUsize.html#method.leading_zeros and in the readme for semver it says `Compiler support: requires rustc 1.31+`. It's only used in two places `src/identifier.rs:265` and `src/identifier.rs:354` according to the compiler.

I guess either the readme needs updating or those two lines can be patched to `repr.get().leading_zeroes()`

**Comment by dtolnay** [comment]
Your build is probably using an old nightly compiler. This crate does not support old nightly compilers. The expectation is that if you are using nightly, you are either pinning both your compiler and your crate versions, or neither your compiler nor your crate versions.
