### ISSUE TITLE
Wildcard VersionReq alongside other requirements

### ISSUE THREAD

**Issue by jonhoo** [dtolnay/semver#253]
I honestly don't know if this is correct behavior or not, but it _seems_ like it should be accepted:

```rust
semver::VersionReq::parse("*, 0.20.0-any").unwrap();
```

gives

```
Error("unexpected character after wildcard in version req")
```

The intent of the version requirement specifier is to match any released version _and_ any pre-release version of 0.20.0 since pre-releases aren't matched by `*`.

Reversing the order gives a different error which makes it seem like `*` is only permitted when used alone:

```rust
semver::VersionReq::parse("0.20.0-any, *").unwrap();
```

gives

```
Error("unexpected character '*' while parsing major version number")
```

**Comment by dtolnay** [comment]
You should go to the Cargo team about syntax changes. This is intentionally not accepted right now. A Cargo RFC may be required.

> The intent of the version requirement specifier is to match any released version _and_ any pre-release version of 0.20.0 since pre-releases aren't matched by `*`.

Note that this is not what comma means. Comma roughly represents intersection, not union. That is why e.g. `>=2, <4` does not match every major version. It would not be my expectation that `*, 0.20.0-any` has a meaning that is different from `^0.20.0-any`.

**Comment by jonhoo** [comment]
> You should go to the Cargo team about syntax changes. This is intentionally not accepted right now. A Cargo RFC may be required.

Fair enough. I wonder if the error could be better though — something along the lines of "wildcard specifiers (*) are only accepted when used on their own".

> > The intent of the version requirement specifier is to match any released version _and_ any pre-release version of 0.20.0 since pre-releases aren't matched by `*`.
> 
> Note that this is not what comma means. Comma roughly represents intersection, not union. That is why e.g. `>=2, <4` does not match every major version. It would not be my expectation that `*, 0.20.0-any` has a meaning that is different from `^0.20.0-any`.

Ooof, of course, you're right. The end of a day that was too long :) And also suggests some additional clean-up I'll have to do at work tomorrow :sweat_smile: I suppose there isn't really a way to specify union today except by keeping multiple `VersionReq`s and using `.iter().any(|vr| vr.matches(...))`.

**Comment by dtolnay** [comment]
Reopening for https://github.com/dtolnay/semver/pull/266#discussion_r799848870.
