### ISSUE TITLE
`is_exact`?

### ISSUE THREAD

**Issue by smoelius** [dtolnay/semver#255]
Semver 0.11.0's `VersionReq` had an `is_exact` method: https://github.com/dtolnay/semver/blob/2748f5cba2ce9c1cab13b0d07fd7a36cf0f3029d/src/version_req.rs#L401

But the latest version's `VersionReq` doesn't seem to have this method.

Is there some way to accomplish what that method did that I am missing?

**Comment by ehuss** [comment]
Something like this should work:

```rust
req.comparators.len() == 1 && {
    let cmp = &req.comparators[0];
    cmp.op == Op::Exact && cmp.minor.is_some() && cmp.patch.is_some()
}
```

**Comment by smoelius** [comment]
Thanks, @ehuss.
