### ISSUE TITLE
Why is Op non-exhaustive?

### ISSUE THREAD

**Issue by infinity0** [dtolnay/semver#262]
I don't see the purpose of this. I am forced to add a `_ => panic!()` field, forcing a compile-time error into an uncertain run-time error. There is only a downside and not an upside.

The usage of non_exhaustive is stated in the RFC https://github.com/rust-lang/rfcs/blob/master/text/2008-non-exhaustive.md is to avoid needless API breakage, forcing downstream users to handle the type generically with `_ => /* generic */`. This is possible for certain things like errors, but most definitely not for `Op`. The only reasonable thing a user can do is to panic. I would rather have a compile-time error than be forced to panic.

**Comment by dtolnay** [comment]
This is intentional to make room for the other semver operators, such as `~>` and `!=`. https://guides.rubygems.org/patterns/#pessimistic-version-constraint
