### ISSUE TITLE
Doc/test requests from an audit from a vendor crate bump

### ISSUE THREAD

**Issue by erickt** [dtolnay/semver#263]
Hi @dtolnay!

@anp and I are updating our vendored semver in Fuchsia, and as part of it we did an audit of the code. We noticed a few things we think would help future audits.

First, in https://fuchsia-review.googlesource.com/c/fuchsia/+/565241/comments/76dac3a6_61040c08 we noticed that we use the mask`0x7f` in a few places. What do you think about lifting out these raw values into a constant or a helper function that could describe what value you're extracting from the u8.

Second, we couldn't find any test that covered the `decode_len_code` codepath in [here](https://fuchsia-review.googlesource.com/c/fuchsia/+/565241/comments/f580dc78_079f4243). Does one cover that part of the code?

Third, in [here](https://fuchsia-review.googlesource.com/c/fuchsia/+/565241/comments/68e2bdb8_c9827571), it'd be helpful if we could have some documentation explaining how `version_req` guarantees that all the values are initialized. Or maybe we could move the recursion of `version_req` into something like:

```
fn version_req(...) -> Result<(), Error> {
    fn inner(...) -> Result<usize, Error> {
    }

    let len = inner(input, out, depth)?;
    // SAFETY: ...
    unsafe { out.set_len(len) }
    Ok(())
}
```

Fourth, in [here](https://fuchsia-review.googlesource.com/c/fuchsia/+/565241/comments/e2f047c0_5542f3fd), `build_identifier` seems to rely on the `input` string to be ASCII-only with no \0 bytes. Could we have add documentation that describes how we know we'll only be getting ASCII characters?

Thanks,
Erick

**Comment by dtolnay** [comment]
Regarding the second one, yes `decode_len_cold` is tested on strings longer than 128 by tests/test_identifier.rs.

For your other comments &mdash; I don't plan to work on any of these myself so I'll go ahead and close the issue, but I would be prepared to consider PRs. Thanks!
