### ISSUE TITLE
Unable to parse v0.0.1-001

### ISSUE THREAD

**Issue by kornelski** [dtolnay/semver#264]
The crates.io registry contains [a crate with version `0.0.1-001`](https://crates.io/crates/bluetooth_client/0.0.1-001), which doesn't parse with semver 1.0.4:

> invalid leading zero in pre-release identifier

**Comment by dtolnay** [comment]
The Cargo folks decided against supporting that, in line with the SemVer spec; numeric prerelease identifiers are not allowed to have a leading zero digit. This crate implements Cargo's interpretation of SemVer, not (old) crates.io's, so it's intentional that that does not parse.
