### ISSUE TITLE
Negation operator

### ISSUE THREAD

**Issue by kornelski** [dtolnay/semver#265]
When a broken crate is released, and isn't yanked, users don't have a future-proof way of specifying version requirements that don't pick the known-broken release.

If a crate `foo 1.2.3` has an unexpected breaking change, its users can require something like `foo = "1, <1.2.3"`, but this excludes *all* future releases of this crate, not just the one known to be broken. This exclusion becomes problematic, because even if 1.2.4 is later released with a fix, it won't be selected, and the range operator may cause dependency conflicts in Cargo.

If semver supported an "or" logical operator, users could specify `1 AND (<1.2.3 OR 1.2.4)`. But the easiest solution may be to support a negation operator that matches every version except the one specified. For example, it could look like: `1, !=1.2.3`. This way the known-broken v1.2.3 won't be picked, but a future release may be.

**Comment by dtolnay** [comment]
This would need to go through a Cargo RFC in https://github.com/rust-lang/rfcs.
