### ISSUE TITLE
v1.0.8 breaks Send/Sync impls on some public structs

### ISSUE THREAD

**Issue by cr0sh** [dtolnay/semver#274]
Hi, the recent release on `semver` has breaking changes regarding `Send`/`Sync` impl on `Prerelease` and `Comparator`. It seems like that the root cause of the breakage is the `NonNull<u8>` field in `Identifier` introduced by https://github.com/dtolnay/semver/pull/273. Would `unsafe impl Send/Sync for Identfier {}` be sufficient to resolve it?

**Comment by dtolnay** [comment]
Fixed in 1.0.9. Sorry about the breakage!
