### ISSUE TITLE
Version Mutability

### ISSUE THREAD

**Issue by nstinus** [dtolnay/semver#297]
Hi, I realize https://github.com/dtolnay/semver/issues/243 removed version mutability. Could it be possible to restore it via an Ext trait?
We were using that to compute version numbers - I am open to alternatives.

Thanks!

**Comment by dtolnay** [comment]
No, I think I would prefer not to have it as part of this crate.

**Comment by nstinus** [comment]
Can you think of an alternative? Apart from using https://github.com/dtolnay/semver/issues/243#issuecomment-854337640 in all the places we require it?
