### ISSUE TITLE
Pre-release versions fail validation

### ISSUE THREAD

**Issue by dtoubelis** [dtolnay/semver#300]
It seems that version like this will not pass the match conditions:

- Required="*", Version="1.0.0-rc1"
- Required="1.0.0", Version="1.0.0-rc1"
- Required="^1.0.0", Version="1.0.0-rc1"

What would be the reason for it? It seems like a valid condition for the match. In fact, it seems like all pre-release versions are deliberately fail validation... Our use case is to use semver matching for licensing purposes and we need to be able to match any pre-release versions.

Also according to Online Semver checker, these are all valid combinations.

- https://jubianchi.github.io/semver-check/#/*/1.0.0-rc1
- https://jubianchi.github.io/semver-check/#/1.0.0/1.0.0-rc1
- https://jubianchi.github.io/semver-check/#/^1.0.0/1.0.0-rc1

It seems like a bug to me.

**Comment by dtolnay** [comment]
This is the behavior specified in https://github.com/semver/semver/blob/efcff2c838c9945f79bfd21c1df0073271bcc29c/ranges.md#semantic-version-range-specification-semver-ranges. It matches npm's semver ranges implementation.

**Comment by dtoubelis** [comment]
Thanks for the reference. It mentions pre-release option, is it something that is currently available? or considered?

...something like `match_prerelase()` call?

**Comment by dtolnay** [comment]
It's not something that has come up in the context of Cargo's needs, which is what this crate is geared around.

**Comment by dtoubelis** [comment]
I'm going to fork the project and implement it myself anyway (I need it rather urgent)... will you accept an MR once done?

**Comment by dtoubelis** [comment]
...actually nevermind, I've found a simple solution for my case - make a copy of `Version` object with `pre` and `build` fields stripped...
