### ISSUE TITLE
Comparison of `Version`s also compares build metadata

### ISSUE THREAD

**Issue by GoldsteinE** [dtolnay/semver#303]
Hi! This code:

```rust
use semver::Version;

fn main() {
    let a = Version::parse("0.0.0+a").unwrap();
    let b = Version::parse("0.0.0+b").unwrap();
    dbg!(a.cmp(&b));
}
```

currently prints 

```
[src/main.rs:6] a.cmp(&b) = Less
```

According to [SemVer 2.0.0 # 10](https://semver.org/#spec-item-10), comparing versions should ignore build metadata. Including it in this comparison also create an inconsistency with `VersionReq` and makes cargo consider version change from `0.0.0+b` to `0.0.0+a` downgrading.

[Crate documentation](https://docs.rs/semver/latest/semver/struct.BuildMetadata.html#total-ordering) also suggests that implementation of `Ord` for `BuildMetadata` is only to allow comparing two `BuildMetadata` values and shouldn’t affect versions.

**Comment by dtolnay** [comment]
`Ord` worked the opposite way in versions 0.11 and older of this crate, and it was undesirable. See #108. Both behaviors are undesirable/confusing in different ways. I think my perspective agrees with https://github.com/dtolnay/semver/issues/108#issuecomment-521762577: the spec says `0.0.0+a` and `0.0.0+b` have the same **precedence** for the purpose of selecting which versions satisfies a particular version req during version selection, but precedence is not the operation that `cmp` implements.

**Comment by GoldsteinE** [comment]
Should it be considered a bug in cargo then? I’d say that calling version change “downgrading” assumes that the new version has lower precedence (it’s also just generally weird, given that build metadata is often stuff like git commit hashes, which are not comparable).

**Comment by dtolnay** [comment]
I created https://github.com/rust-lang/cargo/pull/12796 to change the message in Cargo.
