### ISSUE TITLE
Add a `const_parse` function to parse a subset of semver at compile time

### ISSUE THREAD

**Issue by Enduriel** [dtolnay/semver#320]
Would you be interested in a PR adding a `const_parse` (or similarly named function) which would be able to parse a subset of semver string versions (specifically those with no build/prerelease information) at compile time? This would be a convenience function to allow users to do something like

```rs
semver::Version::const_parse(env!("CARGO_PKG_VERSION"));
```
which could fail to compile, but wouldn't cause runtime errors, meaning they wouldn't have to deal with an additional Result (which I think is quite valuable).

It should also be possible to parse the entire semver version at const time, including the prerelease and build metadata, but that might require restructuring the backend and a memory cost that may be unacceptable for this crate, but I would be interested in adding that as well.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate. But if you end up implementing this as a separate crate, I would be interested to see the result.

**Comment by stegaBOB** [comment]
Hello! I've been messing around with the [`konst`](https://crates.io/crates/konst) crate and stumbled upon this issue. I tried adapting the existing parse implementation to make it const:

```rs
use konst::{option::and_then, parsing::ParseError, slice::get, try_, Parser};
use semver::Version;

pub const fn const_parse_version(s: &str) -> Result<Version, ParseError> {
    let parser = Parser::new(s);
    if parser.is_empty() {
        return Err(parser.into_other_error(&"Empty string"));
    }

    let (major, parser) = try_!(numeric_identifier(parser));
    let parser = try_!(dot(parser));
    let (minor, parser) = try_!(numeric_identifier(parser));
    let parser = try_!(dot(parser));
    let (patch, _parser) = try_!(numeric_identifier(parser));
    Ok(Version::new(major, minor, patch))
}

const fn dot(parser: Parser) -> Result<Parser, ParseError> {
    parser.strip_prefix('.')
}

const fn numeric_identifier(parser: Parser) -> Result<(u64, Parser), ParseError> {
    let mut len = 0;
    let mut value = 0u64;

    let bytes = parser.remainder().as_bytes();
    while let Some(&digit) = get(bytes, len) {
        if digit < b'0' || digit > b'9' {
            break;
        }
        if value == 0 && len > 0 {
            return Err(parser.into_other_error(&"Leading zeros"));
        }
        match and_then!(value.checked_mul(10), |value| value
            .checked_add((digit - b'0') as u64))
        {
            Some(sum) => value = sum,
            None => return Err(parser.into_other_error(&"Overflow")),
        }
        len += 1;
    }

    if len > 0 {
        Ok((value, parser.skip(len)))
    } else if parser.is_empty() {
        Err(parser.into_other_error(&"Unexpected end"))
    } else {
        Err(parser.into_other_error(&"Unexpected character"))
    }
}
```

I think it works in theory, but because `Identifier` manually implements drop (something I discovered after implementing this :sweat_smile:), I don't think Version is really usable at all in const contexts.

Just using the existing const constructor runs into the following error:
```rs
const VERSION: Version = Version::new(1, 2, 3);
const MAJOR: u64 = VERSION.major;
```

```rs
error[E0493]: destructor of `Version` cannot be evaluated at compile-time
 --> src/lib.rs:2:20
  |
2 | const MAJOR: u64 = VERSION.major;
  |                    ^^^^^^^     - value is dropped here
  |                    |
  |                    the destructor for this type cannot be evaluated in constants
```

Not sure if there's really any way around this :(

**Comment by dtolnay** [comment]
You can change `VERSION` to `static` to avoid the "destructor cannot be evaluated at compile time" issue.

```rust
static VERSION: Version = Version::new(1, 2, 3);
const MAJOR: u64 = VERSION.major;
```

(This requires rustc 1.83+)
