### ISSUE TITLE
Feature Request: Add “next_version” Calculation Based on Version Bump and Pre-release Information

### ISSUE THREAD

**Issue by idanfishman** [dtolnay/semver#324]
Hi

I’m working on a project that requires the ability to calculate the "next_version" based on a set of inputs, such as the desired version bump (Major, Minor, Patch), and whether it's a pre-release. Currently, I find it a bit awkward to handle this manually, and as a result, I'm not fully leveraging the SemVer crate's functionality. 

I believe this could be a valuable addition to the crate, as it would streamline the process for others needing similar functionality. Before diving into implementation and creating a PR, I wanted to check if you'd be interested in supporting this feature.

Thanks for your consideration!

**Comment by dtolnay** [comment]
This would be easier to evaluate if you share the exact API or logic that you are interested in adding. But my first impression is that I would prefer not to build this into this crate.

**Comment by idanfishman** [comment]
I’m currently developing a new CLI tool for Semantic Versioning. One of the key features is the ability to bump the version based on user input. Given an input specifying the type of version bump (major, minor, patch) or a prerelease identifier, the tool calculates the next version. This version will then be used for tagging and release purposes.

I'm looking for some version increment method like:
- Increment by PATCH `{major}.{minor}.{patch+1}`
- Increment by MINOR `{major}.{minor+1}.0`
- Increment by MAJOR `{major+1}.0.0`
- Increment PreRelease `{major}.{minor}.{patch}-{prerelease+1}`

**Comment by dtolnay** [comment]
I would leave it to your tool to implement each of these.

Thanks anyway for the suggestion!
