### ISSUE TITLE
Please make Version::parse, Prerelease::new, and BuildMetadata::new const

### ISSUE THREAD

**Issue by zackw** [dtolnay/semver#327]
I would really like to be able to do this:

```
pub const VERSION: Version =
    Version::parse(env!("CARGO_PKG_VERSION")).unwrap();
```

... but that isn't possible because Version::parse isn't a `const fn`.

Neither is it possible for me to do 

```
pub const VERSION: Version = Version {
    major: 1,
    minor: 23,
    patch: 17,
    pre: semver::Prerelease::new("alpha.1").unwrap(),
    build: semver::BuildMetadata::EMPTY,
};
```

because Prerelease::new isn't const either, and similarly for BuildMetadata.

**Comment by dtolnay** [comment]
All of these potentially allocate, so I don't see a path to make them const.

**Comment by zackw** [comment]
Why should they need to allocate???

**Comment by zackw** [comment]
So what? `&'static str` can be arbitrarily large.

**Comment by zackw** [comment]
Hmm, looking at the code for `Identifier`, I see that the issue is that there's currently a short-string representation in use, with an efficient way of telling the difference between an inline string and a heap-allocated string, but (currently) no way to represent a _statically allocated_ long string.  It should not, however, be a problem to add one.  For example, you could tack a "this is (not) on the heap" bit on the beginning of your varint string length prefix.
