### ISSUE TITLE
Allow whitespace-delimited comparator sets

### ISSUE THREAD

**Issue by mbrubeck** [dtolnay/semver#55]
Per https://docs.npmjs.com/misc/semver#ranges, comparators can be joined by whitespace to form a comparator set.  But version_req.rs currently requires comparator sets to be comma-delimited.

`VersionReq::parse(">= 0.4 < 0.5")` currently returns an OpAlreadySet error, but it should be equivalent to `VersionReq::parse(">= 0.4, < 0.5")`.

**Comment by steveklabnik** [comment]
This is hard due to the ambiguity of 

    ">= 0.4 < 0.5"
       ^   ^

these two spaces. Bummer :/

**Comment by steveklabnik** [comment]
with https://github.com/steveklabnik/semver/pull/63 merged this should be a lot easier. well, once the VersionReq parser is ported over, anyway.

**Comment by dtolnay** [comment]
Cargo doesn't accept this style, and so I'll consider it out of scope for this crate. Once there is a Cargo RFC to accept this and Cargo is on board, we can update the implementation here.
