### ISSUE TITLE
Implement hyphen ranges

### ISSUE THREAD

**Issue by mbrubeck** [dtolnay/semver#56]
The version requirement `1.2.3 - 2.3.4` should be equivalent to `>=1.2.3 <=2.3.4`.

Spec: https://docs.npmjs.com/misc/semver#hyphen-ranges-x-y-z-a-b-c

**Comment by dtolnay** [comment]
Per https://github.com/dtolnay/semver/tree/1.0.0-rc.1#scope-of-this-crate, I am going to consider this out of scope for this crate until there is an accepted Cargo RFC. If the Cargo team wants hyphen ranges in Cargo then we can update the implementation here.
