### ISSUE TITLE
Support introspection into a VersionReq

### ISSUE THREAD

**Issue by sfackler** [dtolnay/semver#59]
It'd be nice to be able to look directly at the set of constraints in a `VersionReq`. For example, the implementation of [RFC 1241](https://github.com/rust-lang/rfcs/blob/master/text/1241-no-wildcard-deps.md) wants to check if a `VersionReq` corresponds to a wildcard but the implementation is forced to just compare for equality agaist `VersionReq::parse("*").unwrap()`: https://github.com/rust-lang/cargo/pull/2005/files#diff-e23c793746a7be78139a4e37509a74acR112

**Comment by anguslees** [comment]
+1.  I want to parse a semver and express the implied min/max constraints in a similar constraint syntax (Debian packaging metadata).  It'd be real nice if `VersionReq` predicates were exposed in some way to prevent me having to duplicate all that logic.

**Comment by joshtriplett** [comment]
It looks like semver-parser provides the ability to introspect into its version of VersionReq, but semver has its own version of VersionReq that doesn't allow introspection.

Could semver just use the types from semver-parser, rather than converting to its own?

**Comment by steveklabnik** [comment]
> Could semver just use the types from semver-parser, rather than converting to its own?

I would say yes, but in a slightly different way: they should still convert over, but we should evolve `VersionReq` to be more useful.

Now that we've fully converted over, I want to take a hard look at the whole interface, looking towards a 1.0. These kinds of changes are the things I might want to make.

**Comment by joshtriplett** [comment]
@steveklabnik Why the separate types and conversion between them?

**Comment by steveklabnik** [comment]
They're two separate crates, the conversion means that I don't leak the specific semver-parser into semver's external API.

**Comment by joshtriplett** [comment]
Is there a strong reason to keep them separate rather than unifying them?

**Comment by steveklabnik** [comment]
I like small crates, and keeping concerns separate. One crate for one thing; one handles the conversions, the other has all of the logic for comparisons, etc. it feels like the split between -sys and not to me. Plus, there could be other back ends: maybe that nom parser I tried would work better, or LALRPOP.

But! Part of that is the beauty of < 1.0: I'm not actually sure. We'll see.

**Comment by opilar** [comment]
I don't know how it could be implemented: for now `VersionReq` is just a bunch of `Predicate`'s. For me it's not clear how to get a min and max constrains. 
How can `VersionReq` be exposed actually?

**Comment by dtolnay** [comment]
This is now available in 1.0.0. https://docs.rs/semver/1.0.0-rc.1/semver/struct.VersionReq.html
