### ISSUE TITLE
How to create a match pattern for an Identifier?

### ISSUE THREAD

**Issue by prewk** [dtolnay/semver#68]
``` rust
let v = Version::parse("1.2.3+4").unwrap();
let b = &v.build[0];
```

I'm having trouble getting the `u64` value `4` out of `b`, which seems to be a private enum `Identifier`.  I have solved it like this for now:

``` rust
let v: u64 = b.to_string().parse::<u64>().unwrap();
```

**Comment by steveklabnik** [comment]
Yes, this isn't possible right now, but probably should be. I'm not sure if I should make `Identifier` public or do it some other way.

**Comment by opilar** [comment]
It's public now. We can close this. Or I can add a unit test.

**Comment by dtolnay** [comment]
Yep, this is supported as of 1.0.0.

```rust
fn main() {
    let v = semver::Version::parse("1.2.3+4").unwrap();

    let build = v.build.parse::<u64>().unwrap();
    println!("{}", build);
}
```

**Comment by prewk** [comment]
Amazing, I don't even remember coding in Rust 2015.. 🤔
