### ISSUE TITLE
Do releases better

### ISSUE THREAD

**Issue by steveklabnik** [dtolnay/semver#75]
I've already started bumping versions _after_ we cut a release, rather than before, but we should do better.
1. Changelog
2. Document the actual release process

Anything else?

**Comment by kamalmarhubi** [comment]
I've taken to keeping `publish = false` in my `Cargo.toml` files to prevent accidental releases, and including a `-dev` suffix on versions to further limit damage. I don't have a good way to bump versions automatically though, so it's a bit fiddly.

**Comment by dtolnay** [comment]
Will keep this in mind. :+1:
