### ISSUE TITLE
Please support getting minimum/maximum version from a requirement

### ISSUE THREAD

**Issue by joshtriplett** [dtolnay/semver#86]
Given a version requirement parsed by semver (such as ^3.2), I'd like to ask semver to translate that to a minimum and maximum version (both as `Option<Version>`), similar to the examples shown in http://doc.crates.io/specifying-dependencies.html.  That would make it easier to translate a semver to a version range in a packaging system's dependencies.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate. But with the API of 1.0.0 it's now possible to implement this downstream. If the same logic turns up in lots of projects we can reevaluate including it here.
