### ISSUE TITLE
Add changelog or release notes

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/semver#87]
This is part of [doing releases better](https://github.com/steveklabnik/semver/issues/75). Ideally I would like to see bullet points about what changed in each version on the [releases page](https://github.com/steveklabnik/semver/releases). Why would I upgrade to 0.4.0? What are the risks?

**Comment by steveklabnik** [comment]
Yes, this is a big part of what I want to do for 1.0. I'm not doing it a whole ton right now because the changes are pretty much internal; I've been trying to get rid of the hand-rolled parser for a long time.

I also need to thoroughly document `semver-parser` as well.

**Comment by tjkirch** [comment]
It looks like 1.0 was a breaking release because of (at least) the new Error type.  Would it be possible to add notes to the 1.0 release in GitHub (or wherever is appropriate) about the changes and what users should do to feel confident in upgrading?
