### ISSUE TITLE
Please define Predicate to not allow patch version without minor version

### ISSUE THREAD

**Issue by joshtriplett** [dtolnay/semver#89]
The definition of Predicate includes an `Option<u64>` for minor and for patch; that type would allow a predicate with a patch but no minor.  That causes a `match` expression on a Predicate to complain about missing cases.  Please consider using an enum that doesn't allow that case; for instance:

``` rust
enum Something { M(u64), MM(u64,u64), MMP(u64,u64,u64) }
```

**Comment by dtolnay** [comment]
On balance, I think the current representation is better.
