### ISSUE TITLE
Misleading error for this invalid versionreq

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/semver#95]
Version 0.5.0

`semver::VersionReq::parse("0.14.00").unwrap()` fails with `OpAlreadySet`. Maybe it should fail with `InvalidVersionRequirement`

I assume the current behavior is because it's being treated like `"0.14.0 0"`

**Comment by steveklabnik** [comment]
Yeah, errors are very much not great right now, and one of the reasons this isn't 1.0 yet. Thanks! This is a good case.

**Comment by dtolnay** [comment]
The error in 1.0.0 is a lot better.

```rust
fn main() {
    println!("{}", semver::VersionReq::parse("0.14.00").unwrap_err());
}
```

```console
invalid leading zero in patch version number
```
